# Generated by Django 4.2 on 2023-04-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_obra', models.CharField(max_length=100)),
                ('cod_obra', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
