# Generated by Django 4.2 on 2023-04-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='item',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
