# Generated by Django 4.2 on 2023-04-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dados_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='cod_sol_compra',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
