# Generated by Django 4.2 on 2023-06-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutas',
            name='arquivo',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
