# Generated by Django 4.2 on 2023-06-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_minutas_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='minutas',
            name='previa',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
