# Generated by Django 4.2 on 2023-04-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dados_cod_sol_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='cod_insumo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dados',
            name='desc_insumo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dados',
            name='quant_sol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dados',
            name='nome_obra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
