# Generated by Django 4.2 on 2023-04-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dados_cod_insumo_dados_desc_insumo_dados_quant_sol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='data_sol',
            field=models.DateField(blank=True, null=True),
        ),
    ]
