# Generated by Django 4.2 on 2023-04-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_dados_data_sol'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='data_emissao_pc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dados',
            name='data_sol_cheg_obra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dados',
            name='num_ped_compra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dados',
            name='titles',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
