# Generated by Django 4.2 on 2023-04-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dados_data_emissao_pc_dados_data_sol_cheg_obra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='data_NF',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dados',
            name='prev_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dados',
            name='quant_entregue',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='dados',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
