# Generated by Django 4.2 on 2023-04-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dados_data_nf_dados_prev_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='cod_NF',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dados',
            name='data_entrada_obra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dados',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
