# Generated by Django 4.2 on 2023-04-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dados_cod_nf_dados_data_entrada_obra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='total_sols_compra',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
