# Generated by Django 4.2 on 2023-04-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_dados_total_sols_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('atrasados', models.IntegerField(blank=True, null=True)),
                ('prazo', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
