# Generated by Django 4.2 on 2023-04-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='total_atendido',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
