# Generated by Django 4.2 on 2023-04-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_operations_total_atendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='quant_entregue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dados',
            name='quant_sol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dados',
            name='saldo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
