# Generated by Django 4.2 on 2023-04-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_dados_quant_entregue_alter_dados_quant_sol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='quant_entregue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dados',
            name='quant_sol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dados',
            name='saldo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
