# Generated by Django 4.2 on 2023-04-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_dados_quant_entregue_alter_dados_quant_sol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atrasados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.IntegerField(blank=True, null=True)),
                ('cod_sol_compra', models.IntegerField(blank=True, null=True)),
                ('cod_obra', models.IntegerField(blank=True, null=True)),
                ('cod_insumo', models.IntegerField(blank=True, null=True)),
                ('desc_insumo', models.CharField(blank=True, max_length=100, null=True)),
                ('quant_sol', models.CharField(blank=True, max_length=50, null=True)),
                ('data_sol', models.DateField(blank=True, null=True)),
                ('data_sol_cheg_obra', models.DateField(blank=True, null=True)),
                ('num_ped_compra', models.IntegerField(blank=True, null=True)),
                ('data_emissao_pc', models.DateField(blank=True, null=True)),
                ('prev_entrega', models.DateField(blank=True, null=True)),
                ('quant_entregue', models.CharField(blank=True, max_length=50, null=True)),
                ('saldo', models.CharField(blank=True, max_length=50, null=True)),
                ('data_NF', models.DateField(blank=True, null=True)),
                ('cod_NF', models.CharField(blank=True, max_length=50, null=True)),
                ('data_entrada_obra', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoPrazo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.IntegerField(blank=True, null=True)),
                ('cod_sol_compra', models.IntegerField(blank=True, null=True)),
                ('cod_obra', models.IntegerField(blank=True, null=True)),
                ('cod_insumo', models.IntegerField(blank=True, null=True)),
                ('desc_insumo', models.CharField(blank=True, max_length=100, null=True)),
                ('quant_sol', models.CharField(blank=True, max_length=50, null=True)),
                ('data_sol', models.DateField(blank=True, null=True)),
                ('data_sol_cheg_obra', models.DateField(blank=True, null=True)),
                ('num_ped_compra', models.IntegerField(blank=True, null=True)),
                ('data_emissao_pc', models.DateField(blank=True, null=True)),
                ('prev_entrega', models.DateField(blank=True, null=True)),
                ('quant_entregue', models.CharField(blank=True, max_length=50, null=True)),
                ('saldo', models.CharField(blank=True, max_length=50, null=True)),
                ('data_NF', models.DateField(blank=True, null=True)),
                ('cod_NF', models.CharField(blank=True, max_length=50, null=True)),
                ('data_entrada_obra', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
