# Generated by Django 4.2 on 2023-04-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_atrasados_noprazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='indeterminados',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
