# Generated by Django 4.2 on 2023-04-14 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_operations_indeterminados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dados')),
            ],
        ),
    ]
