# Generated by Django 4.2 on 2023-04-14 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_obras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obras',
            name='obra6',
        ),
        migrations.AddField(
            model_name='obras',
            name='dados',
            field=models.ManyToManyField(blank=True, null=True, to='core.dados'),
        ),
        migrations.CreateModel(
            name='ObraDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dados')),
                ('obras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.obras')),
            ],
        ),
    ]
