# Generated by Django 4.2 on 2023-04-14 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_obras_obra6_obras_dados_obradados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obras',
            name='dados',
        ),
        migrations.AddField(
            model_name='dados',
            name='obras',
            field=models.ManyToManyField(to='core.obras'),
        ),
        migrations.AddField(
            model_name='obras',
            name='obra6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obras_relacionadas', to='core.dados'),
        ),
        migrations.DeleteModel(
            name='ObraDados',
        ),
    ]
