# Generated by Django 4.2 on 2023-04-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_obras_dados_dados_obras_obras_obra6_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('codigo_insumo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_do_insumo', models.CharField(max_length=150)),
                ('qtd_dias', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
