# Generated by Django 4.2 on 2023-04-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_indeterminados_data_prev_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='atrasados',
            name='data_prev_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dados',
            name='data_prev_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noprazo',
            name='data_prev_final',
            field=models.DateField(blank=True, null=True),
        ),
    ]
