# Generated by Django 4.2 on 2023-04-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_atrasados_data_prev_final_dados_data_prev_final_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosAjuCard',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cartao', models.CharField(max_length=100)),
                ('saldoA', models.FloatField()),
                ('saldo', models.FloatField()),
                ('total_saldo', models.FloatField()),
                ('recarga', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DadosRH',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('dias_trabalhados', models.IntegerField()),
                ('valor', models.IntegerField()),
            ],
        ),
    ]
