# Generated by Django 4.2 on 2023-04-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_dadosajucard_dadosrh'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosrh',
            name='pagar',
            field=models.FloatField(null=True),
        ),
    ]
