# Generated by Django 4.2 on 2023-04-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_dadosrh_pagar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosajucard',
            name='cpf',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dadosrh',
            name='cpf',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
