# Generated by Django 4.2 on 2023-04-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_dadosrh_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosrh',
            name='saldo',
            field=models.FloatField(null=True),
        ),
    ]
