# Generated by Django 4.2 on 2023-04-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_dadosrh_saldo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosrh',
            old_name='saldo',
            new_name='total_saldo',
        ),
    ]
