# Generated by Django 4.2 on 2023-04-22 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_saldo_dadosrh_total_saldo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadosrh',
            old_name='total_saldo',
            new_name='total',
        ),
    ]
