# Generated by Django 4.2 on 2023-04-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_dadosajucard_data_planilha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosajucard',
            name='data_planilha',
        ),
        migrations.AddField(
            model_name='dadosrh',
            name='total_atualizado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
