# Generated by Django 4.2 on 2023-04-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_dadosrh_total_atualizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosrh',
            name='total_atualizado',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
