# Generated by Django 4.2 on 2023-04-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_dadosrh_total_atualizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Totais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=100)),
                ('total_pagar', models.CharField(max_length=100)),
                ('total_descontos', models.CharField(max_length=100)),
            ],
        ),
    ]
