# Generated by Django 4.2 on 2023-04-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_totais'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosajucard',
            name='data_planilha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='totais',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
