# Generated by Django 4.2 on 2023-04-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_dadosajucard_data_planilha_alter_totais_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosajucard',
            name='nome_obra',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
