# Generated by Django 4.2 on 2023-04-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_dadosajucard_nome_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosrh',
            name='dias_contabilizados',
            field=models.IntegerField(null=True),
        ),
    ]
