# Generated by Django 4.2 on 2023-04-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_dadosrh_dias_contabilizados'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosrh',
            name='nome_obra',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
