# Generated by Django 4.2 on 2023-04-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_dadosrh_nome_obra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totais',
            name='id',
        ),
        migrations.AddField(
            model_name='totais',
            name='nome_obra',
            field=models.CharField(default=0, max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
