# Generated by Django 4.2 on 2023-04-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_totais_id_totais_nome_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='atrasados',
            name='nome_obra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='indeterminados',
            name='nome_obra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='noprazo',
            name='nome_obra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
