# Generated by Django 4.2 on 2023-04-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_atrasados_nome_obra_indeterminados_nome_obra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
