# Generated by Django 4.2 on 2023-04-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_dados_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
