# Generated by Django 4.2 on 2023-04-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_dados_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados',
            name='obras',
        ),
        migrations.DeleteModel(
            name='Obras',
        ),
    ]
