# Generated by Django 4.2 on 2023-04-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_dados_obras_delete_obras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Atrasados',
        ),
        migrations.DeleteModel(
            name='Indeterminados',
        ),
        migrations.DeleteModel(
            name='NoPrazo',
        ),
    ]
