# Generated by Django 4.2 on 2023-05-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_delete_atrasados_delete_indeterminados_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosComercial',
            fields=[
                ('par', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('data_vcto', models.DateField(blank=True, null=True)),
                ('tipo_condicao', models.CharField(max_length=50)),
                ('id', models.IntegerField(blank=True, null=True)),
                ('vl_original', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ind_dt_base', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ind_dt_calc', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('correcao', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('porc_juro_contr', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('dt_base_juro', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('dt_calc_juro', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('juro_contr', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('porc_multa', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('porc_juros', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('porc_pro_rata', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('multa', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('juros', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pro_rata', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('valor_devido', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('dt_recto', models.DateField(blank=True, null=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('empresa', models.CharField(max_length=100)),
                ('centro_custo', models.CharField(max_length=100)),
                ('titulo_cliente', models.IntegerField(blank=True, null=True)),
                ('cliente', models.CharField(max_length=100)),
                ('data_emissão', models.DateField(blank=True, null=True)),
                ('limite_correcao', models.DateField(blank=True, null=True)),
                ('ultimo_reajuste', models.DateField(blank=True, null=True)),
                ('documento', models.CharField(max_length=100)),
                ('unidades', models.CharField(max_length=100)),
                ('total_lanc', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
