# Generated by Django 4.2 on 2023-05-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_dadoscomercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoscomercial',
            name='centro_custo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dadoscomercial',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dadoscomercial',
            name='documento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dadoscomercial',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dadoscomercial',
            name='tipo_condicao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dadoscomercial',
            name='unidades',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
