# Generated by Django 4.2 on 2023-05-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_dadoscomercial_correcao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesComercial',
            fields=[
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('tituloID', models.IntegerField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('condicoes', models.CharField(max_length=150)),
            ],
        ),
    ]
