# Generated by Django 4.2 on 2023-05-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_clientescomercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosVT',
            fields=[
                ('empresa', models.IntegerField(blank=True, null=True)),
                ('admissao', models.DateField(blank=True, null=True)),
                ('nome', models.CharField(blank=True, max_length=150, null=True)),
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=150, null=True)),
                ('mae', models.CharField(blank=True, max_length=150, null=True)),
                ('nasc', models.DateField(blank=True, null=True)),
                ('cep', models.CharField(blank=True, max_length=150, null=True)),
                ('endereco', models.CharField(blank=True, max_length=150, null=True)),
                ('cidade', models.CharField(blank=True, max_length=150, null=True)),
                ('bairro', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
