# Generated by Django 4.2 on 2023-05-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_dadosvt'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosvt',
            name='numero_endereco',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
