# Generated by Django 4.2 on 2023-05-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_dadosvt_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadoscomercial',
            old_name='data_emissão',
            new_name='data_emissao',
        ),
    ]
