# Generated by Django 4.2 on 2023-05-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_dadoscomercial_id_value_alter_dadoscomercial_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoscomercial',
            name='id_value',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
