# Generated by Django 4.2 on 2023-05-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alter_dadoscomercial_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoscomercial',
            name='reparcelamento',
            field=models.BooleanField(default=False),
        ),
    ]
