# Generated by Django 4.2 on 2023-05-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_dadoscomercial_reparcelamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosrh',
            name='valor_desconto_colaborador',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
