# Generated by Django 4.2 on 2023-05-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_dadosrh_valor_desconto_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosrh',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
