# Generated by Django 4.2 on 2023-05-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_dadosrh_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosrh',
            name='status',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
