# Generated by Django 4.2 on 2023-05-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_dadosrh_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadosrh',
            name='status',
        ),
        migrations.AddField(
            model_name='dadoscomercial',
            name='status',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
