# Generated by Django 4.2 on 2023-05-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_extendeduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosrh',
            name='matricula',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
