# Generated by Django 4.2 on 2023-05-18 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
