# Generated by Django 4.2 on 2023-05-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_dadosrh_codigo_desconto_vt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados',
            old_name='status',
            new_name='status_ped_entregue',
        ),
        migrations.AddField(
            model_name='dados',
            name='status_sol_compra',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
