# Generated by Django 4.2 on 2023-05-25 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_rename_status_dados_status_ped_entregue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados',
            old_name='status_ped_entregue',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='dados',
            name='status_sol_compra',
        ),
    ]
