# Generated by Django 4.2 on 2023-05-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_rename_status_ped_entregue_dados_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dados',
            old_name='status',
            new_name='status_compra',
        ),
        migrations.AddField(
            model_name='dados',
            name='status_entregue',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
